### PR TITLE
Add Q Lockscreen Clock

### PR DESCRIPTION
**Pull request by Ramisky**

### CODE REVIEW

**Comment by eldainosor** [comment]
Nice PR spam + nicer authorship

**Comment by Akianonymus** [comment]
@eldainosor

**Comment by eldainosor** [comment]
@Akianonymus @eldainosor

**Comment by Akianonymus** [comment]
@eldainosor 😂

**Comment by aswin7469** [comment]
@Akianonymus

**Comment by Destiny911gtr** [comment]
@aswin7469 @Destiny911gtr

**Comment by simrat39** [comment]
@Destiny911gtr @show_bobs_and_vegene

**Comment by simrat39** [comment]
@simrat39 @shagbag913

**Comment by Abhinavgupta371** [comment]
@eldainosor Woh

**Comment by dinosnore1** [comment]
@Abhinavgupta371 Meh

**Comment by simrat39** [comment]
@dinosnore1 Bruh

**Comment by dinosnore1** [comment]
@simrat39 U wot m8

**Comment by simrat39** [comment]
@dinosnore1

**Comment by dinosnore1** [comment]
@simrat39 Eat milk

**Comment by simrat39** [comment]
@dinosnore1 Drink biryani

**Comment by dinosnore1** [comment]
@simrat39 Gib

**Comment by simrat39** [comment]
@dinosnore1 🍚🍛

**Comment by Toymakerftw** [comment]
@simrat39 🤔

**Comment by dinosnore1** [comment]
@Toymakerftw Sar phix bholte

**Comment by Abhinavgupta371** [comment]
@dinosnore1 Want sum bun boi

**Comment by dinosnore1** [comment]
@Abhinavgupta371 Yea bean jam bun

**Comment by Abhinavgupta371** [comment]
@dinosnore1 Sand money boi

**Review by Akianonymus — CHANGES_REQUESTED** [review]
Fix authorship

**Review by simrat39 — CHANGES_REQUESTED** [review]
Also squash the other commits

**Comment by Akianonymus** [comment]
Finally!

**Comment by eldainosor** [comment]
> Finally!

it took a while lmao sorry for the notif

**Comment by shagbag913** [comment]
Yo

**Pull request closed without merging**
