### PR TITLE
add fp gesture + expanded volume 

### PR DESCRIPTION
**Pull request by prochy-exe**

### CODE REVIEW

**Comment by prochy-exe** [comment]
New pr waiting

**Comment by eldainosor** [comment]
@ProchyGaming it's like the wine, better with the time

**Comment by Abhinavgupta371** [comment]
@eldainosor yo go ahead nd merge

**Comment by eldainosor** [comment]
@Abhinavgupta371 no u

**Comment by Abhinavgupta371** [comment]
@eldainosor whoi

**Pull request closed without merging**
